#!/usr/bin/env python
# -*- coding: utf-8 -*-

inFich=open("build_number","r")
number=int(inFich.readline().rstrip("\n\r"))+1
inFich.close()

inFich=open("build_number","w")
inFich.write("%s"%number)
inFich.close()

outFich=open("include/version.h","w")
outFich.write("#define BUILD %s"%number)
outFich.close()
